FROM registry.access.redhat.com/ubi9/openjdk-17:1.18-1

USER 0
RUN microdnf install -y gzip xmlstarlet

WORKDIR /app

RUN curl -L -O https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.24/bin/apache-tomcat-10.1.24.tar.gz
RUN tar xzvf apache-tomcat-10.1.24.tar.gz
RUN xmlstarlet ed -L \
    -s '/Server/Service' --type elem -n Connector \
    -a '/Server/Service/Connector[not(@protocol)]' -t attr -n protocol -v 'AJP/1.3' \
    -a '/Server/Service/Connector[@protocol="AJP/1.3"]' -t attr -n port -v 8009 \
    -a '/Server/Service/Connector[@protocol="AJP/1.3"]' -t attr -n redirectPort -v 8443 \
    -a '/Server/Service/Connector[@protocol="AJP/1.3"]' -t attr -n maxParameterCount -v 1000 \
    -a '/Server/Service/Connector[@protocol="AJP/1.3"]' -t attr -n secretRequired -v "false" \
    -a '/Server/Service/Connector[@protocol="AJP/1.3"]' -t attr -n address -v "0.0.0.0" \
    /app/apache-tomcat-10.1.24/conf/server.xml

RUN chown -R default:root /app
RUN chmod g+rw -R /app
RUN find /app -type d -exec chmod g+x {} \;
EXPOSE 8080/tcp
EXPOSE 8009/tcp

RUN cd /app/apache-tomcat-10.1.24/webapps/ && \
    curl -L -O https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war

USER default
CMD ["/app/apache-tomcat-10.1.24/bin/catalina.sh", "run"]
