apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: httpd
spec: {}
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: httpd
  labels:
    build: httpd
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'httpd:latest'
  resources: {}
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: 'registry'
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift-examples/tomcat-example'
    contextDir: httpd
