apiVersion: v1
kind: Service
metadata:
  name: httpd
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: httpd-tls
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: httpd
    deployment: httpd